version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - ./dockerization/hardened/postgres/migrations:/docker-entrypoint-initdb.d
  aucote:
    build:
      context: .
      dockerfile: dockerization/hardened/Dockerfile
      args:
        destEnv: int
    tty: true
    volumes:
      - ./:/src
    environment:
      LD_LIBRARY_PATH: /usr/local/lib
    entrypoint:
      - /entrypoint.sh
    working_dir: /src
    depends_on:
      - postgres