version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - ./dockerization/tests/postgres/migrations:/docker-entrypoint-initdb.d
  aucote:
    build:
      context: .
      dockerfile: dockerization/tests/Dockerfile
      args:
        destEnv: int
    tty: true
    volumes:
      - ./:/src
    environment:
      AUCOTE_TEST_POSTGRES: postgresql://test_aucote:test_aucote@postgres/test_aucote'
      LD_LIBRARY_PATH: /usr/local/lib64
    entrypoint:
      - .ci/run_all.sh
    working_dir: /src
    depends_on:
      - postgres