"""
Mapping services and ports to scans
"""
from tools.hydra.base import HydraScriptTask
from tools.nmap.scripts import *

SERVICE_TO_SCRIPTS_HYDRA = {
    'asterisk': HydraScriptTask,
    'cisco': HydraScriptTask,
    'cisco-enable': HydraScriptTask,
    'cvs': HydraScriptTask,
    'firebird': HydraScriptTask,
    'ftp': HydraScriptTask,
    'ftps': HydraScriptTask,
    'http': HydraScriptTask,
    'https': HydraScriptTask,
    # 'http-post': HydraScriptTask,
    # 'http-head': HydraScriptTask,
    # 'https-get': HydraScriptTask,
    # 'https-post': HydraScriptTask,
    # 'https-head': HydraScriptTask,
    # 'http-get-form': HydraScriptTask,
    # 'http-post-form': HydraScriptTask,
    # 'https-get-form': HydraScriptTask,
    # 'https-post-form': HydraScriptTask,
    # 'http-proxy': HydraScriptTask,
    # 'http-proxy-urlenum': HydraScriptTask,
    'icq': HydraScriptTask,
    'imap': HydraScriptTask,
    'imaps': HydraScriptTask,
    'irc': HydraScriptTask,
    'ldap2': HydraScriptTask,
    # 'ldap2s': HydraScriptTask,
    'ldap3': HydraScriptTask,
    # 'ldap3s': HydraScriptTask,
    # 'ldap3-cram': HydraScriptTask,
    # 'ldap3-crammd5s': HydraScriptTask,
    # 'ldap3-digestmd5': HydraScriptTask,
    # 'ldap3-digestmd5s': HydraScriptTask,
    'mssql': HydraScriptTask,
    'mysql': HydraScriptTask,
    'nntp': HydraScriptTask,
    # 'oracle-listener': HydraScriptTask,
    # 'oracle-sid': HydraScriptTask,
    'pcanywhere': HydraScriptTask,
    'pcnfs': HydraScriptTask,
    'pop3': HydraScriptTask,
    'pop3s': HydraScriptTask,
    'postgres': HydraScriptTask,
    'rdp': HydraScriptTask,
    'redis': HydraScriptTask,
    'rexec': HydraScriptTask,
    'rlogin': HydraScriptTask,
    'rsh': HydraScriptTask,
    'rtsp': HydraScriptTask,
    's7-300': HydraScriptTask,
    'sip': HydraScriptTask,
    'smb': HydraScriptTask,
    'smtp': HydraScriptTask,
    'smtps': HydraScriptTask,
    'smtp-enum': HydraScriptTask,
    'snmp': HydraScriptTask,
    'socks5': HydraScriptTask,
    'ssh': HydraScriptTask,
    'sshkey': HydraScriptTask,
    'svn': HydraScriptTask,
    'teamspeak': HydraScriptTask,
    'telnet': HydraScriptTask,
    'telnets': HydraScriptTask,
    'vmauthd': HydraScriptTask,
    'vnc': HydraScriptTask,
    'xmpp': HydraScriptTask,
}