"""
Structures used by WhatWeb

"""


class WhatWebPlugin(object):
    """
    Output of WhatWeb single plugin

    """
    def __init__(self, **kwargs):
        self.name = kwargs.get('name', None)
        self.version = kwargs.get('version', None)
        self.os = kwargs.get('os', None)
        self.string = kwargs.get('string', [])
        self.account = kwargs.get('account', None)
        self.model = kwargs.get('model', None)
        self.firmware = kwargs.get('firmware', None)
        self.module = kwargs.get('module', None)
        self.filepath = kwargs.get('filepath', None)

    def __str__(self):
        return "{name}: {plugins}".format(name=self.name, plugins=", ".join(self.string))


class WhatWebTarget(object):
    """
    Result of single WhatWeb output line

    """
    def __init__(self, uri=None, status=None, plugins=None):
        self.uri = uri
        self.status = status
        self.plugins = plugins or []

    def __str__(self):
        return "{address} {status_code}:\n{plugins}".format(address=self.uri, status_code=self.status,
                                                            plugins="\n".join([" - {0}".format(str(plugin))
                                                                               for plugin in self.plugins
                                                                               if plugin.string]))


class WhatWebResult(object):
    """
    Result of WhatWeb execution

    """
    def __init__(self, targets=None):
        self.targets = targets or []

    def __str__(self):
        return "\n----------\n".join(str(target) for target in self.targets)


class WhatWebProduct(object):
    """
    Keeps product and vendor of specific application

    """
    def __init__(self, vendor, product):
        self.vendor = vendor
        self.product = product


WHATWEBPLUGINDETAILS = {
    'Apache': [{'product': WhatWebProduct(vendor='apache', product='httpd')}],
    'AChecker': [{'product': WhatWebProduct(vendor='atutor', product='achecker')}],
    'Acme_Serve': [{'product': WhatWebProduct(vendor='acme_labs', product='acme_server')}],
    'activeCollab': [{'product': WhatWebProduct(vendor='activecollab', product='activecollab')}],
    'AdaptCMS': [{'product': WhatWebProduct(vendor='adaptcms', product='adaptcms')}],
    'Adobe-Connect': [{'product': WhatWebProduct(vendor='adobe', product='connect')}],
    'All-in-one-SEO-Pack': [{'product': WhatWebProduct(vendor='semperfiwebdesign', product='all_in_one_seo_pack')}],
    'anyInventory': [{'product': WhatWebProduct(vendor='anyinventory', product='anyinventory')}],
    'AOLserver': [{'product': WhatWebProduct(vendor='aol', product='aol_server')}],
    'Arab-Portal': [{'product': WhatWebProduct(vendor='arabportal', product='arab_portal')}],
    'ashnews': [{'product': WhatWebProduct(vendor='ashwebstudio', product='ashnews')}],
    'ASP-Nuke': [{'product': WhatWebProduct(vendor='asp-nuke', product='asp-nuke')}],
    'ASPThai_Net-Webboard': [{'product': WhatWebProduct(vendor='aspthai.net', product='aspthai_forums')}],
    'aspWebLinks': [{'product': WhatWebProduct(vendor='full_revolution', product='aspweblinks')}],
    'Atlassian-JIRA': [{'product': WhatWebProduct(vendor='atlassian', product='jira')}],
    'AWStats': [{'product': WhatWebProduct(vendor='awstats', product='awstats')}],
    'Axis-Network-Camera': [{'product': WhatWebProduct(vendor='axis', product='network_camera_firmware')}],
    'b2evolution': [{'product': WhatWebProduct(vendor='b2evolution', product='b2evolution')}],
    'BadBlue': [{'product': WhatWebProduct(vendor='working_resources_inc.', product='badblue')}],
    'Basilic': [{'product': WhatWebProduct(vendor='artis.imag', product='basilic')}],
    'Batavi': [{'product': WhatWebProduct(vendor='batavi', product='batavi')}],
    'bbPress': [{'product': WhatWebProduct(vendor='bbpress', product='bbpress')}],
    'BIGACE': [{'product': WhatWebProduct(vendor='bigace', product='bigace')}],
    'BigDump': [{'product': WhatWebProduct(vendor='ozerov', product='bigdump')}],
    'BlackJumboDog': [{'product': WhatWebProduct(vendor='sapporoworks', product='black_jumbodog')}],
    'Blazix': [{'product': WhatWebProduct(vendor='desiderata_software', product='blazix')}],
    'BlogEngine_NET': [{'product': WhatWebProduct(vendor='dotnetblogengine', product='blogengine.net')}],
    'BloofoxCMS': [{'product': WhatWebProduct(vendor='bloofoxcms', product='bloofoxcms')}],
    'BlueDragon': [{'product': WhatWebProduct(vendor='phpbluedragon', product='phpbluedragon_cms')}],
    'boastMachine': [{'product': WhatWebProduct(vendor='boastmachine', product='boastmachine')}],
    'BosClassifieds': [{'product': WhatWebProduct(vendor='bosdev', product='bosclassifieds_classified_ads')}],
    'BrewBlogger': [{'product': WhatWebProduct(vendor='brewblogger', product='brewblogger')}],
    'bSpeak': [{'product': WhatWebProduct(vendor='26thavenue', product='bspeak')}],
    'BugFree': [{'product': WhatWebProduct(vendor='bugfree', product='bugfree')}],
    'BXR': [{'product': WhatWebProduct(vendor='hulihanapplications', product='hulihan_bxr')}],
    'CactuShop': [{'product': WhatWebProduct(vendor='cactusoft', product='cactushop_lite')}],
    'Calendarix': [{'product': WhatWebProduct(vendor='vincent_hor', product='calendarix_advanced')}],
    'CameraLife': [{'product': WhatWebProduct(vendor='camera_life', product='camera_life')}],
    'Campsite': [{'product': WhatWebProduct(vendor='campware.org', product='campsite')}],
    'cApexWEB': [{'product': WhatWebProduct(vendor='shilpisoft', product='capexweb')}],
    'Car-Portal': [{'product': WhatWebProduct(vendor='netartmedia', product='car_portal')}],
    'CAStor': [{'product': WhatWebProduct(vendor='castor', product='castor')}],
    'Caudium': [{'product': WhatWebProduct(vendor='caudium', product='caudium')}],
    'Censura': [{'product': WhatWebProduct(vendor='censura', product='censura')}],
    'Centreon': [{'product': WhatWebProduct(vendor='centreon', product='centreon')}],
    'Chamilo': [{'product': WhatWebProduct(vendor='chamilo', product='chamilo_lms')}],
    'Cherokee': [{'product': WhatWebProduct(vendor='cherokee', product='cherokee_httpd')}],
    'Citrix-NetScaler': [{'product': WhatWebProduct(vendor='citrix', product='netscaler')}],
    'ClipBucket': [{'product': WhatWebProduct(vendor='clip-bucket', product='clipbucket')}],
    'CMScontrol': [{'product': WhatWebProduct(vendor='cmscontrol', product='cmscontrol')}],
    'CMS-Made-Simple': [{'product': WhatWebProduct(vendor='cmsmadesimple', product='cms_made_simple')}],
    'CommonSpot': [{'product': WhatWebProduct(vendor='paperthin', product='commonspot_content_server')}],
    'Concrete5': [{'product': WhatWebProduct(vendor='concrete5', product='concrete')}],
    'Confluence': [{'product': WhatWebProduct(vendor='atlassian', product='confluence')}],
    'ConfTool': [{'product': WhatWebProduct(vendor='conftool', product='conftool')}],
    'Coppermine': [{'product': WhatWebProduct(vendor='coppermine', product='coppermine_photo_gallery')}],
    'coWiki': [{'product': WhatWebProduct(vendor='cowiki', product='cowiki')}],
    'CrushFTP': [{'product': WhatWebProduct(vendor='ben_spink', product='crushftp_ftp_server')}],
    'CubeCart': [{'product': WhatWebProduct(vendor='devellion', product='cubecart')}],
    'CuteFlow': [{'product': WhatWebProduct(vendor='cuteflow-bin', product='cuteflow_bin')}],
    'DaDaBIK': [{'product': WhatWebProduct(vendor='dadabik', product='dadabik')}],
    'Data-ONTAP': [{'product': WhatWebProduct(vendor='netapp', product='clustered_data_ontap')}],
    'DD-WRT': [{'product': WhatWebProduct(vendor='dd-wrt', product='dd-wrt')}],
    'DeluxeBB': [{'product': WhatWebProduct(vendor='deluxebb', product='deluxebb')}],
    'DirectAdmin': [{'product': WhatWebProduct(vendor='jbmc_software', product='directadmin')}],
    'DiY-CMS': [{'product': WhatWebProduct(vendor='diy-cms', product='diy-cms')}],
    'DoceboLMS': [{'product': WhatWebProduct(vendor='docebolms', product='docebolms')}],
    'DokuWiki': [{'product': WhatWebProduct(vendor='andreas_gohr', product='dokuwiki')}],
    'DotNetNuke': [{'product': WhatWebProduct(vendor='dotnetnuke', product='dotnetnuke')}],
    'Dreambox': [{'product': WhatWebProduct(vendor='dreambox', product='dm500c')}],
    'Drupal': [{'product': WhatWebProduct(vendor='drupal', product='drupal')}],
    'Easy-File-Sharing-Web-Server': [{'product': WhatWebProduct(vendor='efssoft',
                                                                product='easy_file_sharing_web_server')}],
    'ECShop': [{'product': WhatWebProduct(vendor='ecshop', product='epshop')}],
    'eDirectory': [{'product': WhatWebProduct(vendor='novell', product='edirectory')}],
    'eGroupWare': [{'product': WhatWebProduct(vendor='egroupware', product='egroupware')}],
    'eLitius': [{'product': WhatWebProduct(vendor='intelliants', product='elitius')}],
    'enVision': [{'product': WhatWebProduct(vendor='rsa', product='envision')}],
    'EPiServer': [{'product': WhatWebProduct(vendor='episerver', product='episerver_cms')}],
    'Epiware': [{'product': WhatWebProduct(vendor='epiware', product='epiware')}],
    'eSyndiCat': [{'product': WhatWebProduct(vendor='esyndicat', product='esyndicat_directory')}],
    'E-Xoopport': [{'product': WhatWebProduct(vendor='e-xoopport', product='e-xoopport')}],
    'Exponent-CMS': [{'product': WhatWebProduct(vendor='exponentcms', product='exponent_cms')}],
    'eXtplorer': [{'product': WhatWebProduct(vendor='extplorer', product='com_extplorer')}],
    'ExtremeWare': [{'product': WhatWebProduct(vendor='extremenetworks', product='extremeware_xos')}],
    'EZCMS': [{'product': WhatWebProduct(vendor='eztechhelp_company', product='ezcms')}],
    'F3Site': [{'product': WhatWebProduct(vendor='f3site', product='f3site')}],
    'FCMS': [{'product': WhatWebProduct(vendor='haudenschilt', product='cpe')}],
    'FileVista': [{'product': WhatWebProduct(vendor='gleamtech', product='filevista')}],
    'fnord': [{'product': WhatWebProduct(vendor='fefe', product='fnord')}],
    'FormMail': [{'product': WhatWebProduct(vendor='matt_wright', product='formmail')}],
    'FortiWeb': [{'product': WhatWebProduct(vendor='fortinet', product='fortiweb')}],
    'FreeNAS': [{'product': WhatWebProduct(vendor='freenas', product='freenas')}],
    'Free-Realty': [{'product': WhatWebProduct(vendor='free_realty', product='free_realty')}],
    'gCards': [{'product': WhatWebProduct(vendor='greg_neustaetter', product='gcards')}],
    'GeekLog': [{'product': WhatWebProduct(vendor='geeklog', product='geeklog')}],
    'GeoServer': [{'product': WhatWebProduct(vendor='geoserver', product='geoserver')}],
    'GetSimple': [{'product': WhatWebProduct(vendor='cagintranetworks', product='getsimple_cms')}],
    'Glossword': [{'product': WhatWebProduct(vendor='glossword', product='glossword')}],
    'Google-Analytics': [{'product': WhatWebProduct(vendor='yoast', product='google_analytics')}],
    'gSOAP': [{'product': WhatWebProduct(vendor='genivia', product='gsoap')}],
    'GuppY': [{'product': WhatWebProduct(vendor='guppy', product='guppy')}],
    'HESK': [{'product': WhatWebProduct(vendor='helpdesk_software', product='hesk')}],
    'Hiki': [{'product': WhatWebProduct(vendor='hiki', product='hiki')}],
    'HiveMail': [{'product': WhatWebProduct(vendor='hivemail', product='hivemail')}],
    'HttpFileServer': [{'product': WhatWebProduct(vendor='rejetto', product='http_file_server')}],
    'Icecast': [{'product': WhatWebProduct(vendor='icecast', product='icecast')}],
    'i-Gallery': [{'product': WhatWebProduct(vendor='blue-collar_productions', product='i-gallery')}],
    'Ikonboard': [{'product': WhatWebProduct(vendor='ikonboard.com', product='ikonboard')}],
    'Imageview': [{'product': WhatWebProduct(vendor='onlinetools.org', product='phpimageview')}],
    'InvisionPowerBoard': [{'product': WhatWebProduct(vendor='invisionpower', product='invision_power_board')}],
    'Ipswitch-IMail': [{'product': WhatWebProduct(vendor='ipswitch', product='imail_server')}],
    'Isolsoft-Support-Center': [{'product': WhatWebProduct(vendor='isolsoft', product='support_center')}],
    'Jamroom': [{'product': WhatWebProduct(vendor='jamroom', product='jamroom')}],
    'JBoss': [{'product': WhatWebProduct(vendor='redhat', product='jboss_enterprise_application_platform')}],
    'jCore': [{'product': WhatWebProduct(vendor='jcore', product='jcore')}],
    'Jcow': [{'product': WhatWebProduct(vendor='jcow', product='jcow')}],
    'Kayako-SupportSuite': [{'product': WhatWebProduct(vendor='kayako', product='supportsuite')}],
    'Kentico-CMS': [{'product': WhatWebProduct(vendor='kentico', product='kentico_cms')}],
    'KnowledgeTree': [{'product': WhatWebProduct(vendor='knowledgetree', product='knowledgetree')}],
    'Kyocera-Printer': [{'product': WhatWebProduct(vendor='kyocera', product='fs-3830n')}],
    'LabVIEW': [{'product': WhatWebProduct(vendor='national_instruments', product='labview')}],
    'Liferay': [{'product': WhatWebProduct(vendor='liferay', product='liferay_enterprise_portal')}],
    'LifeType': [{'product': WhatWebProduct(vendor='lifetype', product='lifetype')}],
    'lighttpd': [{'product': WhatWebProduct(vendor='lighttpd', product='lighttpd')}],
    'LISTSERV': [{'product': WhatWebProduct(vendor='lsoft', product='listserv')}],
    'LiveZilla': [{'product': WhatWebProduct(vendor='livezilla', product='livezilla')}],
    'Loggix': [{'product': WhatWebProduct(vendor='gotdns', product='loggix_project')}],
    'Lotus-Domino': [{'product': WhatWebProduct(vendor='ibm', product='lotus_domino')}],
    'Lyris-ListManager': [{'product': WhatWebProduct(vendor='lyris', product='list_manager')}],
    'Magento': [{'product': WhatWebProduct(vendor='magentocommerc', product='magento')}],
    'MantisBT': [{'product': WhatWebProduct(vendor='mantisbt', product='mantisbt')}],
    'MapServer': [{'product': WhatWebProduct(vendor='university_of_minnesota', product='mapserver')}],
    'Mathopd': [{'product': WhatWebProduct(vendor='mathopd', product='mathopd')}],
    'McAfee-ePolicy-Orchestrator': [{'product': WhatWebProduct(vendor='mcafee', product='epolicy_orchestrator')}],
    'MD-Pro': [{'product': WhatWebProduct(vendor='maxdev', product='md-pro')}],
    'MediaWiki': [{'product': WhatWebProduct(vendor='mediawiki', product='mediawiki')}],
    'MetInfo': [{'product': WhatWebProduct(vendor='metinfo', product='metinfo')}],
    'Microsoft-IIS': [{'product': WhatWebProduct(vendor='microsoft', product='internet_information_server')}],
    'MikroTik-RouterOS': [{'product': WhatWebProduct(vendor='mikrotik', product='routeros')}],
    'MikroTik': [{'product': WhatWebProduct(vendor='mikrotik-routeros.tb', product='routeros')}],
    'MiniBB': [{'product': WhatWebProduct(vendor='minibb', product='minibb')}],
    'MKPortal': [{'product': WhatWebProduct(vendor='mkportal', product='mkportal')}],
    'ModLogAn': [{'product': WhatWebProduct(vendor='modlogan', product='modlogan')}],
    'Moodle': [{'product': WhatWebProduct(vendor='moodle', product='moodle')}],
    'Movable-Type': [{'product': WhatWebProduct(vendor='six_apart', product='movable_type')}],
    'Musicbox': [{'product': WhatWebProduct(vendor='musicbox', product='musicbox')}],
    'MyWebFTP': [{'product': WhatWebProduct(vendor='mywebftp', product='mywebftp')}],
    'Namazu': [{'product': WhatWebProduct(vendor='namazu', product='namazu')}],
    'NaviCOPA': [{'product': WhatWebProduct(vendor='intervations', product='navicopa_web_server')}],
    'net2ftp': [{'product': WhatWebProduct(vendor='net2ftp', product='net2ftp')}],
    'Netref': [{'product': WhatWebProduct(vendor='netref', product='netref')}],
    'Newscoop': [{'product': WhatWebProduct(vendor='sourcefabric', product='newscoop')}],
    'NextGEN-Gallery': [{'product': WhatWebProduct(vendor='alex_rabe', product='nextgen_gallery')}],
    'nginx': [{'product': WhatWebProduct(vendor='igor_sysoev', product='nginx')}],
    'NinkoBB': [{'product': WhatWebProduct(vendor='ninkobb', product='ninkobb')}],
    'Nucleus-CMS': [{'product': WhatWebProduct(vendor='nucleuscms', product='nucleus_cms')}],
    'Nukedit': [{'product': WhatWebProduct(vendor='nukedit', product='nukedit')}],
    'ocPortal': [{'product': WhatWebProduct(vendor='ocportal', product='ocportal')}],
    'OCS-Inventory-NG': [{'product': WhatWebProduct(vendor='ocsinventory-ng', product='ocsinventory_ng')}],
    'Octopussy': [{'product': WhatWebProduct(vendor='8pussy', product='octopussy')}],
    'OpenCart': [{'product': WhatWebProduct(vendor='simple_machines', product='opencart')}],
    'OpenCms': [{'product': WhatWebProduct(vendor='alkacon', product='opencms')}],
    'OpenConf': [{'product': WhatWebProduct(vendor='zakon_group', product='openconf')}],
    'OpenDocMan': [{'product': WhatWebProduct(vendor='opendocman', product='opendocman')}],
    'OpenEMR': [{'product': WhatWebProduct(vendor='openemr', product='openemr')}],
    'openEngine': [{'product': WhatWebProduct(vendor='openengine', product='openengine')}],
    'Openfiler': [{'product': WhatWebProduct(vendor='openfiler', product='openfiler')}],
    'Open-Realty': [{'product': WhatWebProduct(vendor='open-realty', product='open-realty')}],
    'OpenSSL': [{'product': WhatWebProduct(vendor='openssl', product='openssl')}],
    'Open-Xchange': [{'product': WhatWebProduct(vendor='open-xchange', product='ox_guard')}],
    'OpenX': [{'product': WhatWebProduct(vendor='openx', product='openx')}],
    'OrangeHRM': [{'product': WhatWebProduct(vendor='orangehrm', product='orangehrm')}],
    'Orenosv': [{'product': WhatWebProduct(vendor='orenosv', product='orenosv_http_ftp_server')}],
    'OSCommerce': [{'product': WhatWebProduct(vendor='oscommerce', product='oscommerce')}],
    'osTicket': [{'product': WhatWebProduct(vendor='osticket', product='osticket_sts')}],
    'Open-Source-Ticket-Request-System': [{'product': WhatWebProduct(vendor='otrs', product='otrs')}],
    'OvBB': [{'product': WhatWebProduct(vendor='ovbb', product='ovbb')}],
    'OwnServer': [{'product': WhatWebProduct(vendor='anteco_visual_technologies', product='ownserver')}],
    'Pandora-FMS': [{'product': WhatWebProduct(vendor='pandorafms', product='pandora_flexible_monitoring_system')}],
    'PhilBoard': [{'product': WhatWebProduct(vendor='philboard', product='philboard')}],
    'PhotoStore': [{'product': WhatWebProduct(vendor='ktools.net', product='photostore')}],
    'PHP121': [{'product': WhatWebProduct(vendor='php121', product='php121_instant_messenger')}],
    'phpATM': [{'product': WhatWebProduct(vendor='bugada_andrea', product='php_advanced_transfer_manager')}],
    'phpBazar': [{'product': WhatWebProduct(vendor='smartisoft', product='phpbazar')}],
    'phpDenora': [{'product': WhatWebProduct(vendor='denorastats', product='phpdenora')}],
    'PHPDirector': [{'product': WhatWebProduct(vendor='phpdirector', product='phpdirector')}],
    'phpDocumentor': [{'product': WhatWebProduct(vendor='joshua_eichorn', product='phpdocumentor')}],
    'PHPFM': [{'product': WhatWebProduct(vendor='phpfm', product='phpfm')}],
    'phpFox': [{'product': WhatWebProduct(vendor='phpfox', product='phpfox')}],
    'phpFreeChat': [{'product': WhatWebProduct(vendor='phpfreechat', product='phpfreechat')}],
    'PHPGradeBook': [{'product': WhatWebProduct(vendor='phpgradebook', product='php_grade_book')}],
    'phpGraphy': [{'product': WhatWebProduct(vendor='phpgraphy', product='phpgraphy')}],
    'phPhotoAlbum': [{'product': WhatWebProduct(vendor='henning_stoverud', product='phphotoalbum')}],
    'phpLDAPadmin': [{'product': WhatWebProduct(vendor='phpldapadmin', product='phpldapadmin')}],
    'phplist': [{'product': WhatWebProduct(vendor='tincan', product='phplist')}],
    'PHP-Live': [{'product': WhatWebProduct(vendor='php_live', product='php_live')}],
    'phpMoneyBooks': [{'product': WhatWebProduct(vendor='phpmoneybooks', product='phpmoneybooks')}],
    'phpMyFAQ': [{'product': WhatWebProduct(vendor='phpmyfaq', product='phpmyfaq')}],
    'phpMyTourney': [{'product': WhatWebProduct(vendor='phpmytourney', product='phpmytourney')}],
    'phpPgAdmin': [{'product': WhatWebProduct(vendor='phppgadmin', product='phppgadmin')}],
    'phpQuestionnaire': [{'product': WhatWebProduct(vendor='chumpsoft', product='phpquestionnaire')}],
    'phpRaid': [{'product': WhatWebProduct(vendor='spiffyjr', product='phpraid')}],
    'phpRechnung': [{'product': WhatWebProduct(vendor='loenshotel', product='phprechnung')}],
    'phpRemoteView': [{'product': WhatWebProduct(vendor='phpremoteview', product='phpremoteview')}],
    'phpScheduleIt': [{'product': WhatWebProduct(vendor='brickhost', product='phpscheduleit')}],
    'PHPShop': [{'product': WhatWebProduct(vendor='phpshop', product='phpshop')}],
    'phpSysInfo': [{'product': WhatWebProduct(vendor='phpsysinfo', product='phpsysinfo')}],
    'phpVMS': [{'product': WhatWebProduct(vendor='phpvms', product='phpvms')}],
    'phpwcms': [{'product': WhatWebProduct(vendor='phpwcms', product='phpwcms')}],
    'PHPWind': [{'product': WhatWebProduct(vendor='phpwind', product='phpwind')}],
    'PHP-XMLRPC': [{'product': WhatWebProduct(vendor='pear', product='xml_rpc')}],
    'Pi3Web': [{'product': WhatWebProduct(vendor='pi3', product='pi3web')}],
    'PivotX': [{'product': WhatWebProduct(vendor='pivotx', product='pivotx')}],
    'Pixie': [{'product': WhatWebProduct(vendor='getpixie', product='pixie_cms')}],
    'Plesk': [{'product': WhatWebProduct(vendor='parallels', product='parallels_plesk_small_business_panel')}],
    'Pluck-CMS': [{'product': WhatWebProduct(vendor='pluck', product='pluck')}],
    'PluXml': [{'product': WhatWebProduct(vendor='pluxml', product='pluxml')}],
    'Pro-Chat-Rooms': [{'product': WhatWebProduct(vendor='prochatrooms', product='text_chat_rooms')}],
    'PRTG-Network-Monitor': [{'product': WhatWebProduct(vendor='paessler', product='prtg_network_monitor')}],
    'PunBB': [{'product': WhatWebProduct(vendor='punbb', product='punbb')}],
    'qdPM': [{'product': WhatWebProduct(vendor='qdpm', product='qdpm')}],
    'RaidenHTTPD': [{'product': WhatWebProduct(vendor='raidenhttpd', product='raidenhttpd')}],
    'RealVNC': [{'product': WhatWebProduct(vendor='vnc', product='realvnc')}],
    'Redaxscript': [{'product': WhatWebProduct(vendor='redaxscript', product='redaxscript')}],
    'RemotelyAnywhere': [{'product': WhatWebProduct(vendor='remotelyanywhere', product='remotelyanywhere')}],
    'ReOS': [{'product': WhatWebProduct(vendor='elazos', product='reos')}],
    'Request-Tracker': [{'product': WhatWebProduct(vendor='best_practical_solutions', product='request_tracker')}],
    'Resin': [{'product': WhatWebProduct(vendor='caucho_technology', product='resin')}],
    'Restlet-Framework': [{'product': WhatWebProduct(vendor='restlet', product='restlet')}],
    'Roxen': [{'product': WhatWebProduct(vendor='roxen', product='roxen_web_server')}],
    'RunCMS': [{'product': WhatWebProduct(vendor='runcms', product='runcms')}],
    'sabros_us': [{'product': WhatWebProduct(vendor='sabros.us', product='sabros.us')}],
    'SAP-NetWeaver': [{'product': WhatWebProduct(vendor='sap', product='netweaver')}],
    'Savant': [{'product': WhatWebProduct(vendor='michael_lamont', product='savant_webserver')}],
    'Sawmill': [{'product': WhatWebProduct(vendor='sawmill', product='sawmill')}],
    'Sendio-ESP': [{'product': WhatWebProduct(vendor='sendio', product='sendio')}],
    'SePortal': [{'product': WhatWebProduct(vendor='seportal', product='seportal')}],
    'Serendipity': [{'product': WhatWebProduct(vendor='s9y', product='serendipity')}],
    'SilverStripe': [{'product': WhatWebProduct(vendor='silverstripe', product='silverstripe')}],
    'SimpNews': [{'product': WhatWebProduct(vendor='boesch_it-consulting', product='simpnews')}],
    'Sitefinity': [{'product': WhatWebProduct(vendor='telerik', product='sitefinity_cms')}],
    'SmarterMail': [{'product': WhatWebProduct(vendor='smartertools', product='smartermail')}],
    'SmarterStats': [{'product': WhatWebProduct(vendor='smartertools', product='smarterstats')}],
    'SMF': [{'product': WhatWebProduct(vendor='simplemachines', product='smf')}],
    'SmokePing': [{'product': WhatWebProduct(vendor='oetiker', product='smokeping')}],
    'SocketKB': [{'product': WhatWebProduct(vendor='socketkb', product='socketkb')}],
    'Sockso': [{'product': WhatWebProduct(vendor='pu-gh', product='sockso')}],
    'SourceBans': [{'product': WhatWebProduct(vendor='sourcebans-pp_project', product='sourcebans-pp')}],
    'Spiceworks': [{'product': WhatWebProduct(vendor='spiceworks', product='spiceworks')}],
    'SPIP': [{'product': WhatWebProduct(vendor='spip', product='spip')}],
    'SQL-Buddy': [{'product': WhatWebProduct(vendor='sqlbuddy', product='sql_buddy')}],
    'SQLiteManager': [{'product': WhatWebProduct(vendor='sqlite_manager', product='sqlite_manager')}],
    'Squirrelcart': [{'product': WhatWebProduct(vendor='lighthouse_development', product='squirrelcart')}],
    'SquirrelMail': [{'product': WhatWebProduct(vendor='squirrelmail', product='squirrelmail')}],
    'StatusNet': [{'product': WhatWebProduct(vendor='status', product='statusnet')}],
    'Stronghold': [{'product': WhatWebProduct(vendor='redhat', product='stronghold')}],
    'Subrion-CMS': [{'product': WhatWebProduct(vendor='intelliants', product='subrion_cms')}],
    'Sun-GlassFish': [{'product': WhatWebProduct(vendor='oracle', product='glassfish_server')}],
    'Sweetrice': [{'product': WhatWebProduct(vendor='basic-cms', product='sweetrice')}],
    'Symphony-CMS': [{'product': WhatWebProduct(vendor='symphony-cms', product='symphony_cms')}],
    'SyndeoCMS': [{'product': WhatWebProduct(vendor='syndeocms', product='syndeocms')}],
    'TaskFreak': [{'product': WhatWebProduct(vendor='taskfreak', product='taskfreak')}],
    'TCExam': [{'product': WhatWebProduct(vendor='tecnick.com', product='tcexam')}],
    'TestLink': [{'product': WhatWebProduct(vendor='testlink', product='testlink')}],
    'TFTgallery': [{'product': WhatWebProduct(vendor='tftgallery', product='tftgallery')}],
    'TheHostingTool': [{'product': WhatWebProduct(vendor='thehostingtool', product='thehostingtool')}],
    'thttpd': [{'product': WhatWebProduct(vendor='thttpd', product='thttpd_http_server')}],
    'Tinyproxy': [{'product': WhatWebProduct(vendor='tinyproxy', product='tinyproxy')}],
    'TomatoCMS': [{'product': WhatWebProduct(vendor='tomatocms', product='tomatocms')}],
    'Tribiq': [{'product': WhatWebProduct(vendor='tribiq', product='tribiq_cms')}],
    'TVersity': [{'product': WhatWebProduct(vendor='tversity', product='tversity')}],
    'TypoLight': [{'product': WhatWebProduct(vendor='typolight', product='typolight_webcms')}],
    'Uebimiau-Webmail': [{'product': WhatWebProduct(vendor='uebimiau', product='uebimiau')}],
    'Ultimate-Bulletin-Board': [{'product': WhatWebProduct(vendor='infopop', product='ultimate_bulletin_board')}],
    'Ultraseek': [{'product': WhatWebProduct(vendor='infoseek', product='ultraseek_server')}],
    'Ultrastats': [{'product': WhatWebProduct(vendor='ultrastats', product='ultrastats')}],
    'Uniform-Server': [{'product': WhatWebProduct(vendor='uniformserver', product='uniformserver')}],
    'vbPortal': [{'product': WhatWebProduct(vendor='vbportal', product='vbportal')}],
    'VBulletin': [{'product': WhatWebProduct(vendor='jelsoft', product='vbulletin')}],
    'VideoDB': [{'product': WhatWebProduct(vendor='mambo', product='videodb')}],
    'Viking': [{'product': WhatWebProduct(vendor='robtex', product='viking_server')}],
    'Viscacha': [{'product': WhatWebProduct(vendor='viscacha', product='viscacha')}],
    'VP-ASP': [{'product': WhatWebProduct(vendor='virtual_programming', product='vp-asp')}],
    'vqServer': [{'product': WhatWebProduct(vendor='vqsoft', product='vqserver')}],
    'vTigerCRM': [{'product': WhatWebProduct(vendor='vtiger', product='vtiger_crm')}],
    'W3-Total-Cache': [{'product': WhatWebProduct(vendor='w3edge', product='total_cache')}],
    'w-agora': [{'product': WhatWebProduct(vendor='w-agora', product='w-agora')}],
    'WampServer': [{'product': WhatWebProduct(vendor='wampserver', product='wampserver')}],
    'Webbler': [{'product': WhatWebProduct(vendor='tincan', product='webbler_cms')}],
    'webfs': [{'product': WhatWebProduct(vendor='webfs', product='webfs')}],
    'Webgrind': [{'product': WhatWebProduct(vendor='joakim_nygard', product='webgrind')}],
    'Webmatic': [{'product': WhatWebProduct(vendor='valarsoft', product='webmatic')}],
    'Webmedia-Explorer': [{'product': WhatWebProduct(vendor='webmedia_explorer', product='webmedia_explorer')}],
    'WebPress': [{'product': WhatWebProduct(vendor='goywp', product='webpress')}],
    'webSPELL': [{'product': WhatWebProduct(vendor='webspell', product='webspell')}],
    'WebspotBlogging': [{'product': WhatWebProduct(vendor='webspot', product='webspotblogging')}],
    'WHMCS': [{'product': WhatWebProduct(vendor='whmcompletesolution', product='whmcompletesolution')}],
    'Wing-FTP-Server': [{'product': WhatWebProduct(vendor='wftpserver', product='wing_ftp_server')}],
    'WolfCMS': [{'product': WhatWebProduct(vendor='wolfcms', product='wolf_cms')}],
    'Wordpress-Contact-Form': [{'product': WhatWebProduct(vendor='cfdbplugin', product='contact_form_db')}],
    'WordPress-Mobile-Pack': [{'product': WhatWebProduct(vendor='wordpress_mobile_pack_project',
                                                         product='wordpress_mobile_pack')}],
    'wpQuiz': [{'product': WhatWebProduct(vendor='wire_plastic_design', product='wpquiz')}],
    'X7-Chat': [{'product': WhatWebProduct(vendor='x7_group', product='x7_chat')}],
    'XchangeBoard': [{'product': WhatWebProduct(vendor='xchangeboard', product='xchangeboard')}],
    'Xerver': [{'product': WhatWebProduct(vendor='xerver', product='xerver')}],
    'xGB': [{'product': WhatWebProduct(vendor='xgb', product='xgb')}],
    'Xitami': [{'product': WhatWebProduct(vendor='imatix', product='xitami')}],
    'eXtreme-Message-Board': [{'product': WhatWebProduct(vendor='xmb_forum', product='xmb')}],
    'xt-Commerce': [{'product': WhatWebProduct(vendor='xt-commerce', product='xt:commerce')}],
    'XWiki': [{'product': WhatWebProduct(vendor='xwiki', product='xwiki')}],
    'Yamamah': [{'product': WhatWebProduct(vendor='yamamah', product='yamamah')}],
    'Zenoss-Core': [{'product': WhatWebProduct(vendor='zenoss', product='zenoss')}],
    'Zeus-Web-Server': [{'product': WhatWebProduct(vendor='zeus', product='zeus_web_server')}],
    '360-Web-Manager': [{'product': WhatWebProduct(vendor='360_web_manager', product='360_web_manager')}],
    '3COM-NBX': [{'product': WhatWebProduct(vendor='3com', product='webbngss3nbxnts')}],
    '4D': [{'product': WhatWebProduct(vendor='4d', product='webstar')}],
    '4images': [{'product': WhatWebProduct(vendor='4homepages', product='4images')}],
    '68-Classifieds-Script': [{'product': WhatWebProduct(vendor='68_classifieds', product='68_classifieds')}],
    '6kbbs': [{'product': WhatWebProduct(vendor='6kbbs', product='6kbbs')}],
    'Aardvark-Topsites-PHP': [{'product': WhatWebProduct(vendor='avatic', product='aardvark_topsites_php')}],
    'activeWeb-Content-Server': [{'product': WhatWebProduct(vendor='activeweb', product='contentserver')}],
    'Advanced-Guestbook': [{'product': WhatWebProduct(vendor='advanced_guestbook', product='advanced_guestbook')}],
    'Advantech-WebAccess': [{'product': WhatWebProduct(vendor='advantech', product='webaccess')}],
    'AEF': [{'product': WhatWebProduct(vendor='anelectron', product='advanced_electron_forum')}],
    'AfterLogic-WebMail-Pro': [{'product': WhatWebProduct(vendor='afterlogic', product='webmail_pro')}],
    'Allegro-RomPager': [{'product': WhatWebProduct(vendor='allegrosoft', product='rompager')}],
    'Apache-Archiva': [{'product': WhatWebProduct(vendor='apache', product='archiva')}],
    'Apache-Cocoon': [{'product': WhatWebProduct(vendor='apache', product='cocoon')}],
    'Apache-Struts': [{'product': WhatWebProduct(vendor='apache', product='struts')}],
    'Apache-Tomcat ': [{'product': WhatWebProduct(vendor='apache', product='tomcat')}],
    'ArGoSoft-Mail-Server': [{'product': WhatWebProduct(vendor='argosoft', product='argosoft_mail_server')}],
    'ArticlePublisherPRO': [{'product': WhatWebProduct(vendor='scripts_frenzy', product='article_publisher_pro')}],
    'Artiphp-CMS': [{'product': WhatWebProduct(vendor='artiphp', product='artiphp_cms')}],
    'Contao': [{'product': WhatWebProduct(vendor='contao', product='contao_cms')}],
    'FluxBB': [{'product': WhatWebProduct(vendor='fluxbb', product='fluxbb')}],
    'Jenkins': [{'product': WhatWebProduct(vendor='jenkins', product='jenkins')}],
    'JEUS': [{'product': WhatWebProduct(vendor='tmaxsoft', product='jeus')}],
    'JGS-Portal': [{'product': WhatWebProduct(vendor='jgs-xa', product='jgs-portal')}],
    'Jigsaw': [{'product': WhatWebProduct(vendor='w3c', product='jigsaw')}],
    'Jive-SBS': [{'product': WhatWebProduct(vendor='jive_software', product='jive')}],
    'Joomla': [{'product': WhatWebProduct(vendor='joomla', product=r'joomla\!')}],
    'Karrigell': [{'product': WhatWebProduct(vendor='karrigell', product='karrigell')}],
    'Kerio-Connect': [{'product': WhatWebProduct(vendor='kerio', product='connect')}],
    'Kerio-WebSTAR': [{'product': WhatWebProduct(vendor='kerio', product='webstar')}],
    'Kerio-WinRoute-Firewall': [{'product': WhatWebProduct(vendor='kerio', product='winroute_firewall')}],
    'LightNEasy': [{'product': WhatWebProduct(vendor='lightneasy', product='lightneasy')}],
    'phpBB': [{'product': WhatWebProduct(vendor='phpbb', product='phpbb')}],
    'phpMyAdmin': [{'product': WhatWebProduct(vendor='phpmyadmin', product='phpmyadmin')}],
    'TYPO3': [{'product': WhatWebProduct(vendor='typo3', product='typo3')}],
    'Vanilla-Forums': [{'product': WhatWebProduct(vendor='vanillaforums', product='vanilla_forums')}],
    'WordPress': [{'product': WhatWebProduct(vendor='wordpress', product='wordpress')}],
    'WSN-Forum': [{'product': WhatWebProduct(vendor='wsn', product='forum')}],
    'WSN-Gallery': [{'product': WhatWebProduct(vendor='wsn', product='gallery')}],
    'WSN-Knowledge-Base': [{'product': WhatWebProduct(vendor='wsn', product='knowledge_base')}],
    'X10media-MP3-Search-Engine': [{'product': WhatWebProduct(vendor='x10media', product='mp3_search_engine')}],
    'Zabbix': [{'product': WhatWebProduct(vendor='zabbix', product='zabbix')}],
    'ZoneMinder': [{'product': WhatWebProduct(vendor='zoneminder', product='zoneminder')}],
    'PHP': [{'product': WhatWebProduct(vendor='php', product='php')}],
    'phpinfo': [{'product': WhatWebProduct(vendor='php', product='php')}]
}
